services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-volume-data:/data
    networks:
      - redis-network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight-data:/db
    networks:
      - redis-network

volumes:
  redis-volume-data:
  redisinsight-data:

networks:
  redis-network:
